// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk-i-aSL3L3smEFKN4mQVd-go2z4xObaU',
    appId: '1:650300046203:android:fe62653e23e2183187dbde',
    messagingSenderId: '650300046203',
    projectId: 'proyectopasantiatales',
    storageBucket: 'proyectopasantiatales.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0beO-VkCnTaZRoVGT-0Joz2pk07_cSiQ',
    appId: '1:650300046203:ios:b6e3de7676543a5c87dbde',
    messagingSenderId: '650300046203',
    projectId: 'proyectopasantiatales',
    storageBucket: 'proyectopasantiatales.appspot.com',
    androidClientId: '650300046203-d6siiehvbvot0ug01gr9k6v84k00mvhq.apps.googleusercontent.com',
    iosClientId: '650300046203-pc74lj3skippadhd322urkiiabkfc497.apps.googleusercontent.com',
    iosBundleId: 'com.example.cuentosPasantia',
  );
}
